### ISSUE TITLE
Models with canvas views cause error

### ISSUE THREAD

**Issue by Melody8988** [archi-contribs/script-plugin#1]
I've noticed a possible bug with the script plugin, or there's something wrong with the model I am attempting to draw an html report for. 

I've made this dummy model that seems to break all other models with **canvas views** inside. 
I get this error:

`java.lang.Exception: Import of image failed !`

When I loop through a database to draw a bunch of models, the script stops at that model that's causing this error and doesn't draw any of the html reports that follow behind in the database.

I've tried making new models with **canvas views** and they work fine, but when I try to run them in the same script with this "problem model" any other models that contained canvas views become corrupted and also give the same error and become a "problem model" themselves. 

Here's the zip to the "problem model": 
[GithubModel.archimate.zip](https://github.com/archi-contribs/script-plugin/files/2822312/GithubModel.archimate.zip)

You may need to run :

OPTION ExitArchi on 
 SELECT GithubModel FROM DATABASE archimodels
 REPORT HTML TO /path/GithubModel
 CLOSE 

...a couple times to recreate the error. 

Let me know if more detailed instructions are needed in order to recreate the problem.

**Comment by Phillipus** [comment]
~@herve91 Herve, is this for you?~

Cancel that, I thought I was in the Archi Github tracker. ;-)

**Comment by Melody8988** [comment]
No worries @Phillipus 
After a bit more testing, it looks like a model that has a view with a template (an example, the ArchiMate 3.0 Notation Overview template) you cannot run an HTML report for it with this script. 
Sometimes, you have to try the script twice before you get the error: 
`java.lang.Exception: Import of image failed !`

**Comment by herve91** [comment]
Hi,

My apologies forthis late answer, I've not been very available these days. I'll check your zip file and let you know if I can reproduce your error and find what happens.

Best regards
Hervé

**Comment by herve91** [comment]
Hi,

The issue comes from the fact that the model class has not yet created its archiveManager when instantiated by the script plugin. The next version of the database plugin will include the fix.

Best regards
Hervé
